// Code generated by Slice Machine. DO NOT EDIT.

import ButtonLink from './ButtonLink';
import FullWidthPhoto from './FullWidthPhoto';
import HalfWidthPhoto from './HalfWidthPhoto';

export {
	ButtonLink,
	FullWidthPhoto,
	HalfWidthPhoto,
};

export const components = {
	button_link: ButtonLink,
	full_width_photo: FullWidthPhoto,
	half_width_photo: HalfWidthPhoto,
};
